#!/usr/bin/env ruby

##
# Even Fibonacci numbers
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def problem2(num)
  f = [1,2]
  f.push(f[-2..-1].reduce(:+)) until f[-1] >= num
  f.select{|n| n.even?}.reduce(:+)
end

p problem2(4000000)
